### ISSUE TITLE
Not all commands return responses if a video isn't found.

### ISSUE THREAD

**Issue by hohonuuli** [jaywardell/SharktopodaTest#4] opened 2016-08-29 19:17 UTC
Jay, I'm running tests with the commands when no video is open in Sharktopoda. Some will return failed messages, other's are not returning a message even if one is expected (at the very least, it should be a status:failed message.

Here's a short example:

### With a video open with correct UUID

This works as expect when there is a video with matching UUID.

```
SEND OPEN -> {
  "command": "open",
  "url": "file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.mov",
  "uuid": "4f8058ef-9bd2-4c33-85a0-f6a7b336a4a3"
}
OPEN RESPONSE <-  {"response":"open","status":"ok"}

SEND PLAY -> {
  "command": "play",
  "rate": 1.0,
  "uuid": "4f8058ef-9bd2-4c33-85a0-f6a7b336a4a3"
}
PLAY RESPONSE <-  {"response":"play","status":"ok","uuid":"4f8058ef-9bd2-4c33-85a0-f6a7b336a4a3"}

SEND REQUEST_VIDEO_INFO -> {
  "command": "request video information",
  "uuid": "4f8058ef-9bd2-4c33-85a0-f6a7b336a4a3"
}
REQUEST_VIDEO_INFO RESPONSE <-  {"response":"request video information","uuid":"4f8058ef-9bd2-4c33-85a0-f6a7b336a4a3","status":"ok","url":"file:\/Volumes\/LBD2\/i2map\/2015-06-15_Test_Dives_4.mov"}

```

### With no window with that UUID

Not sure what's going on here. I'm quessing Sharktopoda isn't responding to the play request, so I get the same stuff from the last reponse. Don't know why the request video info if responding with a play message.

```
SEND OPEN -> {
  "command": "open",
  "url": "file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx",
  "uuid": "5a417ede-d2ad-4c5d-a9b3-fc6df452938e"
}
OPEN RESPONSE <-  {"response":"open","status":"failed"}

SEND PLAY -> {
  "command": "play",
  "rate": 1.0,
  "uuid": "5a417ede-d2ad-4c5d-a9b3-fc6df452938e"
}
PLAY RESPONSE <-  {"response":"open","status":"failed"}

SEND REQUEST_VIDEO_INFO -> {
  "command": "request video information",
  "uuid": "5a417ede-d2ad-4c5d-a9b3-fc6df452938e"
}
REQUEST_VIDEO_INFO RESPONSE<-  {"response":"play","status":"failed"}
```

**Comment by hohonuuli** [comment] 2016-08-29 19:18
So just to summarize, if a response is expected for a command, a response should always be returned, even if it's just to say failed.

**Comment by jaywardell** [comment] 2016-08-29 22:32
I've pushed a fix that always sends a response, even on error, if the command is meant to give a response.  Still, the particular case you sent me seems to be doing something different.  It appears to be receiving the response for the previous call.  Even stranger, it appears that the response is being received JUST BEFORE the next command is sent.

Here's some output from my own test client:

`8/29/16, 6:27:39 PM:	message sent to 127.0.0.1:19000 at 2016-08-29 22:27:39 +0000: {
  "command": "open",
  "url": "file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx",
  "uuid": "5a417ede-d2ad-4c5d-a9b3-fc6df452938e"
}
8/29/16, 6:27:39 PM:	received response:{
    response = open;
    status = failed;
}
8/29/16, 6:27:39 PM:	command "open" was unsuccessful
8/29/16, 6:27:49 PM:	received response:{
    response = open;
    status = failed;
}
8/29/16, 6:27:49 PM:	command "open" was unsuccessful
8/29/16, 6:27:49 PM:	message sent to 127.0.0.1:19000 at 2016-08-29 22:27:49 +0000: {
  "command": "play",
  "url": "file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx",
  "uuid": "5a417ede-d2ad-4c5d-a9b3-fc6df452938e"
}
8/29/16, 6:28:00 PM:	received response:{
    response = play;
    status = failed;
}
8/29/16, 6:28:00 PM:	command "play" was unsuccessful
8/29/16, 6:28:00 PM:	message sent to 127.0.0.1:19000 at 2016-08-29 22:28:00 +0000: {
  "command": "pause",
  "url": "file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx",
  "uuid": "5a417ede-d2ad-4c5d-a9b3-fc6df452938e"
}
`

Notice the timestamps between 'message sent' and 'received response'.  I'm trying to track this down, but can you verify my theory?

**Comment by jaywardell** [comment] 2016-08-29 22:34
Also, toggling Sharktopoda's server off and on seems to correct this issue.

**Comment by hohonuuli** [comment] 2016-08-29 22:39
Is it sending the failed to open response twice?

**Comment by hohonuuli** [comment] 2016-08-29 22:42
Just a note that I'm still running into the same problem with the latest fix.

**Comment by jaywardell** [comment] 2016-08-29 22:42
for me, it sent the 'failed to open' at 6:27:39, just after I sent the command and again at 6:27:49, just after I hit the button to send the 'play' command but before the client sent it (at least that's what the log says).

**Comment by jaywardell** [comment] 2016-08-29 22:43
Is it a similar pattern for you?

**Comment by jaywardell** [comment] 2016-08-29 22:45
also, if I open a video that does exist first, then try to open one that doesn't, then I get expected behavior...

**Comment by hohonuuli** [comment] 2016-08-29 22:48
I've seen things like this happen with UDP where something like this is going on:


### this is OK

```
send first command -> Sharktopoda
read response: {"response": "1"} <- Sharktopoda
send second command -> Sharktopoda
read response: {"response": "2"} <- Sharktopoda
```

### This bad

```
send first command -> Sharktopoda
// WHOOPS! Forgot to read the reponse. In this case, we'll get response to the 
// 2nd command will be whatever was supposed to be read by the first command
send second command -> Sharktopoda
read response: {"response": "1"} <- Sharktopoda
```

**Comment by jaywardell** [comment] 2016-08-29 22:52
That's something like what I think is happening.  The response is sitting, waiting to be read, but somehow not being read. btw, in the bad case from your original post, you can watch Sharktopoda's log and see that it sends the response, or at least thinks it does.

**Comment by hohonuuli** [comment] 2016-08-29 23:01
Yep. It looks like it's sending to responses when open fails. I've attached the logs from both the remote app and Sharktopoda for the same session

### Log From Remote App

```
2016-08-29 15:58:39 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaVideoIO - org.mbari.vcr4j.sharktopoda.commands.OpenCmd@d44fc21 -> {
  "command": "open",
  "url": "file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx",
  "uuid": "8f717042-66ee-4081-aab8-7f08bcaf5810"
}
2016-08-29 15:58:39 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaResponseParser - org.mbari.vcr4j.sharktopoda.commands.OpenCmd@d44fc21 <-  {"response":"open","status":"failed"}
2016-08-29 15:58:40 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaVideoIO - PLAY -> {
  "command": "play",
  "rate": 1.0,
  "uuid": "8f717042-66ee-4081-aab8-7f08bcaf5810"
}
2016-08-29 15:58:40 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaResponseParser - PLAY <-  {"response":"open","status":"failed"}
2016-08-29 15:58:40 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaVideoIO - REQUEST_VIDEO_INFO -> {
  "command": "request video information",
  "uuid": "8f717042-66ee-4081-aab8-7f08bcaf5810"
}
2016-08-29 15:58:40 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaResponseParser - REQUEST_VIDEO_INFO <-  {"response":"play","status":"failed"}
```

### Log from Sharktopoda

```
8/29/16, 3:57:59 PM:	Server Started on port 8800
8/29/16, 3:58:39 PM:	Received JSON from 127.0.0.1: {
    command = open;
    url = "file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx";
    uuid = "8f717042-66ee-4081-aab8-7f08bcaf5810";
}
8/29/16, 3:58:39 PM:	got a command: Command:open
["uuid": 8f717042-66ee-4081-aab8-7f08bcaf5810, "url": file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx]
8/29/16, 3:58:39 PM:	Sending Response VerboseSharkResponse(command: Command:open
["uuid": 8f717042-66ee-4081-aab8-7f08bcaf5810, "url": file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx], success: SharktopodaTest.SharkResponseStatus.failed, error: Optional(Error Domain=NSCocoaErrorDomain Code=260 "The file “2015-06-15_Test_Dives_4.movx” couldn’t be opened because there is no such file." UserInfo={NSURL=file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx, NSFilePath=/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx, NSUnderlyingError=0x618000041b00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}), allowSendingOnFailure: true, payload: [:])
8/29/16, 3:58:39 PM:	Response Sent
8/29/16, 3:58:39 PM:	Sending Response VerboseSharkResponse(command: Command:open
["uuid": 8f717042-66ee-4081-aab8-7f08bcaf5810, "url": file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx], success: SharktopodaTest.SharkResponseStatus.failed, error: Optional(Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." UserInfo={NSLocalizedDescription=The requested URL was not found on this server., NSUnderlyingError=0x60800004a3e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}), allowSendingOnFailure: true, payload: [:])
8/29/16, 3:58:39 PM:	Response Sent
8/29/16, 3:58:40 PM:	Received JSON from 127.0.0.1: {
    command = play;
    rate = 1;
    uuid = "8f717042-66ee-4081-aab8-7f08bcaf5810";
}
8/29/16, 3:58:40 PM:	got a command: Command:play
["uuid": 8f717042-66ee-4081-aab8-7f08bcaf5810, "rate": 1]
8/29/16, 3:58:40 PM:	Sending Response VerboseSharkResponse(command: Command:play
["uuid": 8f717042-66ee-4081-aab8-7f08bcaf5810, "rate": 1], success: SharktopodaTest.SharkResponseStatus.failed, error: Optional(Error Domain=VideoPlayerCoordinator Code=12 "No video is available with UUID 8F717042-66EE-4081-AAB8-7F08BCAF5810" UserInfo={NSLocalizedDescription=No video is available with UUID 8F717042-66EE-4081-AAB8-7F08BCAF5810}), allowSendingOnFailure: true, payload: [:])
8/29/16, 3:58:40 PM:	Response Sent
8/29/16, 3:58:40 PM:	Received JSON from 127.0.0.1: {
    command = "request video information";
    uuid = "8f717042-66ee-4081-aab8-7f08bcaf5810";
}
8/29/16, 3:58:40 PM:	got a command: Command:getVideoInfo
["uuid": 8f717042-66ee-4081-aab8-7f08bcaf5810]
8/29/16, 3:58:40 PM:	Sending Response VerboseSharkResponse(command: Command:getVideoInfo
["uuid": 8f717042-66ee-4081-aab8-7f08bcaf5810], success: SharktopodaTest.SharkResponseStatus.failed, error: Optional(Error Domain=VideoPlayerCoordinator Code=14 "There is no focused video window" UserInfo={NSLocalizedDescription=There is no focused video window}), allowSendingOnFailure: true, payload: [:])
8/29/16, 3:58:40 PM:	Response Sent
```

**Comment by jaywardell** [comment] 2016-08-29 23:03
Well that would probably cause a problem...  Let me look around.

**Comment by jaywardell** [comment] 2016-08-29 23:16
Yes, I validate any file: URLs before creating a window for them, but I was failing to return after I called the callback in that case.  So I was sending 2 responses to one command, and the second response was hanging around, not getting received.

I'm going to call this "response squashing", unless there's a more technical name I don't know about.

**Comment by jaywardell** [comment] 2016-08-29 23:17
fix pushed, let me know if it works for you...

**Comment by hohonuuli** [comment] 2016-08-29 23:41
__Much better!__. The simple test case is working now. Here's the output:


### Remote App
```
2016-08-29 16:39:50 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaVideoIO - org.mbari.vcr4j.sharktopoda.commands.OpenCmd@d44fc21 -> {
  "command": "open",
  "url": "file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx",
  "uuid": "8e681306-9b53-40ca-bb63-6f022a639eaf"
}
2016-08-29 16:39:50 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaResponseParser - org.mbari.vcr4j.sharktopoda.commands.OpenCmd@d44fc21 <-  {"response":"open","status":"failed"}
2016-08-29 16:39:51 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaVideoIO - PLAY -> {
  "command": "play",
  "rate": 1.0,
  "uuid": "8e681306-9b53-40ca-bb63-6f022a639eaf"
}
2016-08-29 16:39:51 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaResponseParser - PLAY <-  {"response":"play","status":"failed"}
2016-08-29 16:39:51 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaVideoIO - REQUEST_VIDEO_INFO -> {
  "command": "request video information",
  "uuid": "8e681306-9b53-40ca-bb63-6f022a639eaf"
}
2016-08-29 16:39:51 [main] DEBUG org.mbari.vcr4j.sharktopoda.SharktopodaResponseParser - REQUEST_VIDEO_INFO <-  {"response":"request video information","status":"failed"}
```

### Sharktopoda

```
8/29/16, 4:39:38 PM:	Server Started on port 8800
8/29/16, 4:39:50 PM:	Received JSON from 127.0.0.1: {
    command = open;
    url = "file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx";
    uuid = "8e681306-9b53-40ca-bb63-6f022a639eaf";
}
8/29/16, 4:39:50 PM:	got a command: Command:open
["uuid": 8e681306-9b53-40ca-bb63-6f022a639eaf, "url": file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx]
8/29/16, 4:39:50 PM:	Sending Response VerboseSharkResponse(command: Command:open
["uuid": 8e681306-9b53-40ca-bb63-6f022a639eaf, "url": file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx], success: SharktopodaTest.SharkResponseStatus.failed, error: Optional(Error Domain=NSCocoaErrorDomain Code=260 "The file “2015-06-15_Test_Dives_4.movx” couldn’t be opened because there is no such file." UserInfo={NSURL=file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx, NSFilePath=/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.movx, NSUnderlyingError=0x6100000431e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}), allowSendingOnFailure: true, payload: [:])
8/29/16, 4:39:50 PM:	Response Sent
8/29/16, 4:39:51 PM:	Received JSON from 127.0.0.1: {
    command = play;
    rate = 1;
    uuid = "8e681306-9b53-40ca-bb63-6f022a639eaf";
}
8/29/16, 4:39:51 PM:	got a command: Command:play
["uuid": 8e681306-9b53-40ca-bb63-6f022a639eaf, "rate": 1]
8/29/16, 4:39:51 PM:	Sending Response VerboseSharkResponse(command: Command:play
["uuid": 8e681306-9b53-40ca-bb63-6f022a639eaf, "rate": 1], success: SharktopodaTest.SharkResponseStatus.failed, error: Optional(Error Domain=VideoPlayerCoordinator Code=12 "No video is available with UUID 8E681306-9B53-40CA-BB63-6F022A639EAF" UserInfo={NSLocalizedDescription=No video is available with UUID 8E681306-9B53-40CA-BB63-6F022A639EAF}), allowSendingOnFailure: true, payload: [:])
8/29/16, 4:39:51 PM:	Response Sent
8/29/16, 4:39:51 PM:	Received JSON from 127.0.0.1: {
    command = "request video information";
    uuid = "8e681306-9b53-40ca-bb63-6f022a639eaf";
}
8/29/16, 4:39:51 PM:	got a command: Command:getVideoInfo
["uuid": 8e681306-9b53-40ca-bb63-6f022a639eaf]
8/29/16, 4:39:51 PM:	Sending Response VerboseSharkResponse(command: Command:getVideoInfo
["uuid": 8e681306-9b53-40ca-bb63-6f022a639eaf], success: SharktopodaTest.SharkResponseStatus.failed, error: Optional(Error Domain=VideoPlayerCoordinator Code=14 "There is no focused video window" UserInfo={NSLocalizedDescription=There is no focused video window}), allowSendingOnFailure: true, payload: [:])
8/29/16, 4:39:51 PM:	Response Sent

```

**Comment by hohonuuli** [comment] 2016-08-29 23:41
Don't close this yet. I'm running more elaborate tests.

**Comment by hohonuuli** [comment] 2016-08-29 23:45
For my notes, I ran the following sequence of commands __with no video__ with a 500ms interval between commands. The output was correct.

```java
List<VideoCommand> cmds = Arrays.asList(new OpenCmd(url),
                VideoCommands.PLAY,
                SharkCommands.SHOW,
                SharkCommands.REQUEST_VIDEO_INFO,
                SharkCommands.REQUEST_ALL_VIDEO_INFOS,
                VideoCommands.REQUEST_ELAPSED_TIME,
                VideoCommands.REQUEST_INDEX,
                VideoCommands.REQUEST_STATUS,
                new SeekElapsedTimeCmd(Duration.ofMillis(3000)),
                new ShuttleCmd(0.5),
                new ShuttleCmd(-0.5),
                new ShuttleCmd(0.1),
                new ShuttleCmd(-0.1),
                VideoCommands.PAUSE,
                SharkCommands.CLOSE,
                VideoCommands.REQUEST_INDEX);
```

**Comment by hohonuuli** [comment] 2016-08-29 23:46
Ran a repeat of the above at 50ms intervals and output was AOK.

**Closed** 2016-08-29 23:49 UTC
